apiVersion: v1
kind: Service
metadata:
  labels:
    service: simple-reverse-proxy
  name: simple-reverse-proxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: simple-reverse-proxy